---

- name: plugins | Download and install plugins
  sudo: yes
  get_url:
    url="{{item.url}}"
    dest="{{sonar_ext_dir}}"
  with_items: sonar_plugins
  sudo_user: "{{sonar_owner}}"
  notify: restart sonar
  when: "sonar_plugins is defined and sonar_plugins | count > 0"
